### ISSUE TITLE
Zenodo Publish Fails with Default Description

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/gwvolman#95] opened 2019-12-03 19:22 UTC
Publishing a Tale that has the default description fails to publish to Zenodo. This might not technically be a bug, but we might have a better way to handle missing descriptions.

Steps to reproduce
1. Use the `zenodo-publishing` dashboard branch
2. Create a Tale
3. Add some files to it
4. Publish it (make sure you have your account configured)
5. Note the error below in the gwvolman logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 518, in publish
    provider.publish()
  File "/gwvolman/gwvolman/lib/zenodo.py", line 199, in publish
    deposition = self.create_deposition()
  File "/gwvolman/gwvolman/lib/zenodo.py", line 141, in create_deposition
    zenodo_metadata = self.get_tale_metadata()
  File "/gwvolman/gwvolman/lib/zenodo.py", line 123, in get_tale_metadata
    self.manifest["schema:description"]
  File "/gwvolman/gwvolman/lib/zenodo.py", line 53, in _render_description
    html = parser.convert(description)
  File "/usr/local/lib/python3.5/dist-packages/markdown/core.py", line 252, in convert
    if not source.strip():
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bodom0015** [comment] 2019-12-03 19:58
Possibly a duplicate of https://github.com/whole-tale/girder_wholetale/issues/373, but it's unclear where this change should be tracked

**Closed** 2019-12-18 19:41 UTC
